# Generated by Django 4.2.2 on 2023-07-10 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    replaces = [('people', '0002_alter_person_options'),
                ('people', '0003_remove_person_departments_remove_person_events'),
                ('people', '0004_person_is_user_historicalperson'),
                ('people', '0005_historicalperson_id_user_person_id_user'),
                ('people', '0006_rename_id_user_historicalperson_user_instance_and_more'),
                ('people', '0007_alter_person_user_instance')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('surname', 'name', 'patronymic'), 'verbose_name': 'Человек',
                     'verbose_name_plural': 'Люди'},
        ),
        migrations.RemoveField(
            model_name='person',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='person',
            name='events',
        ),
        migrations.AddField(
            model_name='person',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='Является ли пользователем'),
        ),
        migrations.CreateModel(
            name='HistoricalPerson',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('surname', models.CharField(verbose_name='Фамилия')),
                ('name', models.CharField(verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, null=True, verbose_name='Отчество')),
                ('organisation', models.CharField(verbose_name='Организация')),
                ('bmstu_group', models.CharField(blank=True, null=True, verbose_name='Учебная группа (МГТУ)')),
                ('phone_number', models.CharField(blank=True, verbose_name='Телефонный номер')),
                ('tg_username', models.CharField(blank=True, verbose_name='Тег в телеграме')),
                ('is_user', models.BooleanField(default=False, verbose_name='Является ли пользователем')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('user_instance', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                    to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя')),
            ],
            options={
                'verbose_name': 'historical Человек',
                'verbose_name_plural': 'historical Люди',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='person',
            name='user_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
    ]
