# Generated by Django 4.2.2 on 2023-07-09 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('surname', 'name', 'patronymic'), 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
    ]
