# Generated by Django 4.2.2 on 2023-07-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='bmstu_group',
            field=models.CharField(blank=True, default='', verbose_name='Учебная группа (МГТУ)'),
            preserve_default=False,
        ),
    ]
