# Generated by Django 4.2.2 on 2023-07-13 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalperson',
            name='bmstu_group',
            field=models.CharField(blank=True, null=False, verbose_name='Учебная группа (МГТУ)'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bmstu_group',
            field=models.CharField(blank=True, null=False, verbose_name='Учебная группа (МГТУ)'),
        ),
    ]
