# Generated by Django 4.2.2 on 2023-07-04 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id_supervisor',
            new_name='supervisors',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='id_teacher',
            new_name='teachers',
        ),
    ]
