# Generated by Django 4.2.2 on 2023-07-10 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    replaces = [('events', '0004_alter_event_options'), ('events', '0005_event_listeners'),
                ('events', '0006_historicalevent')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_add_fields'),
        ('people', '0003_remove_person_departments_remove_person_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('dt_start', 'name'), 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='listeners',
            field=models.ManyToManyField(blank=True, related_name='event_listeners_match', to='people.person',
                                         verbose_name='Слушатели'),
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('dt_start', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('dt_finish', models.DateField(blank=True, null=True, verbose_name='Дата конца')),
                ('t_start', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('t_finish', models.TimeField(blank=True, null=True, verbose_name='Время конца')),
                ('frequently', models.IntegerField(blank=True, null=True, verbose_name='Частота занятий')),
                ('audience_num', models.CharField(blank=True, null=True, verbose_name='Номер аудитории')),
                ('status', models.IntegerField(default=0, verbose_name='Статус')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Событие',
                'verbose_name_plural': 'historical События',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
