# Generated by Django 4.2.2 on 2023-07-03 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('descr', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отедел',
                'verbose_name_plural': 'Отеделы',
                'ordering': ('-name',),
            },
        ),
    ]
