# Generated by Django 4.2.2 on 2023-07-06 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [('departments', '0002_initial'), ('departments', '0003_alter_department_options')]

    dependencies = [
        ('people', '0001_initial'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='id_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='people.person', verbose_name='Руководитель'),
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-name',), 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
    ]
