# Generated by Django 4.2.2 on 2023-07-10 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    replaces = [('departments', '0004_alter_department_options'), ('departments', '0005_department_activists'),
                ('departments', '0006_historicaldepartment')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('people', '0003_remove_person_departments_remove_person_events'),
        ('people', '0004_person_is_user_historicalperson'),
        ('departments', '0002_add_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('name',), 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AddField(
            model_name='department',
            name='activists',
            field=models.ManyToManyField(blank=True, related_name='department_activists_match', to='people.person',
                                         verbose_name='Активисты'),
        ),
        migrations.CreateModel(
            name='HistoricalDepartment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('descr', models.TextField(verbose_name='Описание')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type',
                 models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                   to=settings.AUTH_USER_MODEL)),
                ('id_supervisor', models.ForeignKey(blank=True, db_constraint=False, null=True,
                                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                                    to='people.person', verbose_name='Руководитель')),
            ],
            options={
                'verbose_name': 'historical Отдел',
                'verbose_name_plural': 'historical Отделы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
