# Generated by Django 4.2.2 on 2023-07-05 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-name',), 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
    ]
