# Generated by Django 4.2.2 on 2023-07-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('departments', '0007_rename_id_supervisor_department_supervisor_instance_and_more'),
                ('departments', '0008_department_group_historicaldepartment_group'),
                ('departments', '0009_remove_department_group_and_more')]

    dependencies = [
        ('departments', '0003_add_historical'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='id_supervisor',
            new_name='supervisor_instance',
        ),
        migrations.RenameField(
            model_name='historicaldepartment',
            old_name='id_supervisor',
            new_name='supervisor_instance',
        ),
        migrations.AddField(
            model_name='department',
            name='permissions',
            field=models.CharField(choices=[('crud', 'Чтение, изменение, добавление'), ('readonly', 'Только чтение'),
                                            ('none', 'Нет прав')], default='none', verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='permissions',
            field=models.CharField(choices=[('crud', 'Чтение, изменение, добавление'), ('readonly', 'Только чтение'),
                                            ('none', 'Нет прав')], default='none', verbose_name='Уровень доступа'),
        ),
    ]
