# Generated by Django 4.2.2 on 2023-07-11 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_department_options_squashed_0006_historicaldepartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='id_supervisor',
            new_name='supervisor_instance',
        ),
        migrations.RenameField(
            model_name='historicaldepartment',
            old_name='id_supervisor',
            new_name='supervisor_instance',
        ),
    ]
