# Generated by Django 4.2.2 on 2023-07-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departments', '0007_rename_id_supervisor_department_supervisor_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.group', verbose_name='Уровень доступа'),
        ),
    ]
