# Generated by Django 4.2.2 on 2023-07-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0008_department_group_historicaldepartment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicaldepartment',
            name='group',
        ),
        migrations.AddField(
            model_name='department',
            name='permissions',
            field=models.CharField(choices=[('crud', 'Чтение, изменение, добавление'), ('readonly', 'Только чтение'), ('none', 'Нет прав')], default='none', verbose_name='Уровень доступа'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='permissions',
            field=models.CharField(choices=[('crud', 'Чтение, изменение, добавление'), ('readonly', 'Только чтение'), ('none', 'Нет прав')], default='none', verbose_name='Уровень доступа'),
        ),
    ]
