name: Django CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_NAME }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Fill env-file
        run: |
          echo APP_KEY=${{ secrets.APP_KEY }} >> .env
          echo DB_HOST=${{ env.DB_HOST }} >> .env
          echo DB_PORT=${{ env.DB_PORT }} >> .env
          echo DB_USER=${{ env.DB_USER }} >> .env
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
          echo DB_NAME=${{ env.DB_NAME }} >> .env
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
      - name: Run Tests
        run: |
          cd IIS
          python manage.py test
